// Mocks generated by Mockito 5.4.6 from annotations
// in food_delivery/test/features/product/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:food_delivery/features/product/data/datasources/local/product_local_data_source.dart'
    as _i7;
import 'package:food_delivery/features/product/data/datasources/remote/product_remote_data_source.dart'
    as _i3;
import 'package:food_delivery/features/product/data/models/product_model.dart'
    as _i2;
import 'package:food_delivery/features/product/domain/entities/product.dart'
    as _i6;
import 'package:food_delivery/features/product/domain/entities/product_result.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i3.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ProductModel>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<List<_i2.ProductModel>> getRecommendedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendedProducts, []),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<List<_i2.ProductModel>> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [category]),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<_i2.ProductModel> toggleFavorite(
    String? productId,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [productId, isFavorite]),
            returnValue: _i4.Future<_i2.ProductModel>.value(
              _FakeProductModel_0(
                this,
                Invocation.method(#toggleFavorite, [productId, isFavorite]),
              ),
            ),
          )
          as _i4.Future<_i2.ProductModel>);

  @override
  _i4.Future<_i2.ProductModel> getProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue: _i4.Future<_i2.ProductModel>.value(
              _FakeProductModel_0(
                this,
                Invocation.method(#getProductById, [productId]),
              ),
            ),
          )
          as _i4.Future<_i2.ProductModel>);

  @override
  _i4.Future<List<_i2.ProductModel>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<void> addProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.ProductResult> watchAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTasks, []),
            returnValue: _i4.Stream<_i5.ProductResult>.empty(),
          )
          as _i4.Stream<_i5.ProductResult>);

  @override
  _i4.Stream<_i5.ProductResult> watchRecommendedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchRecommendedProducts, []),
            returnValue: _i4.Stream<_i5.ProductResult>.empty(),
          )
          as _i4.Stream<_i5.ProductResult>);

  @override
  _i4.Stream<_i5.ProductResult> watchProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsByCategory, [category]),
            returnValue: _i4.Stream<_i5.ProductResult>.empty(),
          )
          as _i4.Stream<_i5.ProductResult>);

  @override
  _i4.Stream<_i6.ProductEntity?> watchProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductById, [productId]),
            returnValue: _i4.Stream<_i6.ProductEntity?>.empty(),
          )
          as _i4.Stream<_i6.ProductEntity?>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i7.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ProductModel>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<_i2.ProductModel?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i4.Future<_i2.ProductModel?>.value(),
          )
          as _i4.Future<_i2.ProductModel?>);

  @override
  _i4.Future<void> updateProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#insertProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.ProductResult> watchAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTasks, []),
            returnValue: _i4.Stream<_i5.ProductResult>.empty(),
          )
          as _i4.Stream<_i5.ProductResult>);

  @override
  _i4.Stream<List<_i6.ProductEntity>> watchFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#watchFavorites, []),
            returnValue: _i4.Stream<List<_i6.ProductEntity>>.empty(),
          )
          as _i4.Stream<List<_i6.ProductEntity>>);

  @override
  _i4.Future<List<_i2.ProductModel>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<List<_i2.ProductModel>> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [category]),
            returnValue: _i4.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Stream<_i5.ProductResult> watchProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsByCategory, [category]),
            returnValue: _i4.Stream<_i5.ProductResult>.empty(),
          )
          as _i4.Stream<_i5.ProductResult>);

  @override
  _i4.Stream<_i6.ProductEntity?> watchProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductById, [id]),
            returnValue: _i4.Stream<_i6.ProductEntity?>.empty(),
          )
          as _i4.Stream<_i6.ProductEntity?>);

  @override
  _i4.Future<void> toggleFavorite(String? id, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id, isFavorite]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
