// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZSSvvac9BpVFEWplvgVtf4PAaWSVum4',
    appId: '1:339996996772:web:ee80b9b17d4dc40278a231',
    messagingSenderId: '339996996772',
    projectId: 'food-delivery-97aee',
    authDomain: 'food-delivery-97aee.firebaseapp.com',
    storageBucket: 'food-delivery-97aee.firebasestorage.app',
    measurementId: 'G-2DEYW3WNX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALenn33r-PyZwtO8bDYHBbMh7GL4NSo6k',
    appId: '1:339996996772:android:a214368cc4c6eb6a78a231',
    messagingSenderId: '339996996772',
    projectId: 'food-delivery-97aee',
    storageBucket: 'food-delivery-97aee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazWDYJymj1cc7-x9qLsLmzT16PPLU1i8',
    appId: '1:339996996772:ios:f101121311b2e20e78a231',
    messagingSenderId: '339996996772',
    projectId: 'food-delivery-97aee',
    storageBucket: 'food-delivery-97aee.firebasestorage.app',
    iosBundleId: 'com.mid.foodDelivery',
  );
}
