// Mocks generated by Mockito 5.4.6 from annotations
// in food_delivery/test/features/product/domain/usecases/get_products_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:food_delivery/features/product/data/models/product_model.dart'
    as _i6;
import 'package:food_delivery/features/product/domain/entities/product.dart'
    as _i3;
import 'package:food_delivery/features/product/domain/entities/product_result.dart'
    as _i2;
import 'package:food_delivery/features/product/domain/repositories/product_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductResult_0 extends _i1.SmartFake implements _i2.ProductResult {
  _FakeProductResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductEntity_1 extends _i1.SmartFake implements _i3.ProductEntity {
  _FakeProductEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i4.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProductResult> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i5.Future<_i2.ProductResult>.value(
              _FakeProductResult_0(this, Invocation.method(#getProducts, [])),
            ),
          )
          as _i5.Future<_i2.ProductResult>);

  @override
  _i5.Future<_i2.ProductResult> getRecommendedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendedProducts, []),
            returnValue: _i5.Future<_i2.ProductResult>.value(
              _FakeProductResult_0(
                this,
                Invocation.method(#getRecommendedProducts, []),
              ),
            ),
          )
          as _i5.Future<_i2.ProductResult>);

  @override
  _i5.Future<_i2.ProductResult> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [category]),
            returnValue: _i5.Future<_i2.ProductResult>.value(
              _FakeProductResult_0(
                this,
                Invocation.method(#getProductsByCategory, [category]),
              ),
            ),
          )
          as _i5.Future<_i2.ProductResult>);

  @override
  _i5.Future<_i3.ProductEntity> toggleFavorite(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [productId]),
            returnValue: _i5.Future<_i3.ProductEntity>.value(
              _FakeProductEntity_1(
                this,
                Invocation.method(#toggleFavorite, [productId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductEntity>);

  @override
  _i5.Future<_i3.ProductEntity> getProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue: _i5.Future<_i3.ProductEntity>.value(
              _FakeProductEntity_1(
                this,
                Invocation.method(#getProductById, [productId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductEntity>);

  @override
  _i5.Stream<_i2.ProductResult> watchAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTasks, []),
            returnValue: _i5.Stream<_i2.ProductResult>.empty(),
          )
          as _i5.Stream<_i2.ProductResult>);

  @override
  _i5.Stream<_i2.ProductResult> watchRecommendedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchRecommendedProducts, []),
            returnValue: _i5.Stream<_i2.ProductResult>.empty(),
          )
          as _i5.Stream<_i2.ProductResult>);

  @override
  _i5.Stream<_i2.ProductResult> watchProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsByCategory, [category]),
            returnValue: _i5.Stream<_i2.ProductResult>.empty(),
          )
          as _i5.Stream<_i2.ProductResult>);

  @override
  _i5.Stream<_i3.ProductEntity?> watchProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductById, [productId]),
            returnValue: _i5.Stream<_i3.ProductEntity?>.empty(),
          )
          as _i5.Stream<_i3.ProductEntity?>);

  @override
  _i5.Future<_i2.ProductResult> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i5.Future<_i2.ProductResult>.value(
              _FakeProductResult_0(
                this,
                Invocation.method(#searchProducts, [query]),
              ),
            ),
          )
          as _i5.Future<_i2.ProductResult>);

  @override
  _i5.Future<void> addProduct(_i6.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
